version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd arfna-main
      - mvn clean install
artifacts:
  files:
    - livewar-assembly/target/livewar-example.war
