version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -f arfna-main/pom.xml
artifacts:
  files:
    - livewar-assembly/target/livewar-example.war
